language: python

python:
  - "2.7"

branches:
  only:
    - master

install:
  - pip install pep8
  - pip install pylint
  - pip install -r requirements/edx/pre.txt
  - pip install -r requirements/edx/github.txt
  - pip install -r requirements/edx/local.txt
  - pip install -r requirements/edx/base.txt
  - pip install -r requirements/edx/paver.txt
  - pip install -r requirements/edx/post.txt
  - pip install -r requirements/philu/base.txt
  - pip install -r requirements/edx/testing.txt

script:
  # Run pep8 on all .py files in all subfolders
  # ignore E402: module level import not at top of file
  - find . -name \*.py -exec pep8 --max-line-length=120 {} +
  - pylint --disable=all --enable=function-redefined,undefined-variable,unused-variable
  - paver test_system -t lms/djangoapps/onboarding --fasttest
