language: python

python:
  - "2.7"

sudo: required

git:
  depth: false

branches:
  only:
    - develop
    - master

services:
  - mysql

before_install:
  - sudo rm -vf /etc/apt/sources.list.d/*riak*
  - sudo apt-get update -qq
  - sudo xargs -a requirements/system/ubuntu/apt-packages.txt
  - sudo apt-get install -qq --fix-missing

  # Decrypt configuration file
  - openssl aes-256-cbc -K $encrypted_347d15b64587_key -iv $encrypted_347d15b64587_iv -in configurations.tar.enc -out configurations.tar -d
  # Extract configuration files
  - tar xvf configurations.tar -C ../
  # Copy ssh token
  - cp ../id_rsa ~/.ssh/
  # Clone PhilU custom theme
  - git clone git@github.com:philanthropy-u/philu-edx-theme.git

install:
  - pip install -r requirements/edx/pre.txt
  - pip install -r requirements/edx/github.txt
  - pip install -r requirements/edx/local.txt
  - pip install -r requirements/edx/base.txt
  - pip install -r requirements/edx/paver.txt
  - sudo apt-get update
  - sudo apt-get install libxmlsec1-dev
  - pip install -r requirements/edx/post.txt
  - pip install -r requirements/philu/base.txt
  - pip install -r requirements/edx/testing.txt
  - pip install google-compute-engine
  - pip install pep8
  - pip install pylint

before_script:
  - mysql -e 'create database edxtest;' -u root

script:
  # Run pep8 on all .py files in all subfolders
  # ignore E402: module level import not at top of file
  - sudo service mongod start
  # - find openedx/features/course_card -name \*.py -exec pep8 --max-line-length=120 {} +
  # - pylint openedx/features/course_card --disable R,C,W,E --enable=function-redefined,undefined-variable,unused-variable
  - ./scripts/travis-ci-tests.sh

env:
  global:
    - CI_NODE_TOTAL=2
  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1
