language: python

python:
  - "2.7"

sudo: required

git:
  depth: false

branches:
  only:
    - develop
    - master

services:
  - mysql

before_install:
  - sudo rm -vf /etc/apt/sources.list.d/*riak*
  - sudo apt-get update -qq
  - sudo xargs -a requirements/system/ubuntu/apt-packages.txt
  - sudo apt-get install -qq --fix-missing
  - openssl aes-256-cbc -K $encrypted_347d15b64587_key -iv $encrypted_347d15b64587_iv -in configurations.tar.enc -out configurations.tar -d
  - tar xvf configurations.tar -C ../
  - cp ../id_rsa ~/.ssh/
  - git clone git@github.com:philanthropy-u/philu-edx-theme.git
  - cd philu-edx-theme
  - pwd

install:
  # - pip install -r requirements/edx/pre.txt
  # - pip install -r requirements/edx/github.txt
  # - pip install -r requirements/edx/local.txt
  # - pip install -r requirements/edx/base.txt
  # - pip install -r requirements/edx/paver.txt
  # - sudo apt-get update
  # - sudo apt-get install libxmlsec1-dev
  # - pip install -r requirements/edx/post.txt
  # - pip install -r requirements/philu/base.txt
  # - pip install -r requirements/edx/testing.txt
  # - pip install google-compute-engine
  - pip install pep8
  - pip install pylint

before_script:
  - mysql -e 'create database edxtest;' -u root

script:
  # Run pep8 on all .py files in all subfolders
  # ignore E402: module level import not at top of file
  - sudo service mongod start
  # - find lms/djangoapps/onboarding -name \*.py -exec pep8 --max-line-length=120 {} +
  # - pylint lms/djangoapps/onboarding --disable=all --enable=function-redefined,undefined-variable,unused-variable
  # - paver test_system -t openedx/features/course_card/tests --fasttest
