language: python

python:
  - "2.7"

install:
  - pip install pep8
  - pip install pylint

script:
  # Run pep8 on all .py files in all subfolders
  # ignore E402: module level import not at top of file
  - find . -name \*.py -exec pep8 --max-line-length=120 {} +
  - pylint --disable=all --enable=function-redefined,undefined-variable,unused-variable
  
