comment: off

codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down

  status:
    project:
      default:
        target: 85%
        threshold: 10%
    patch: false
