# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:2.7.14

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            sudo apt install software-properties-common
            
      - run:
          name: install dependencies
          command: |
            sudo add-apt-repository ppa:chris-lea/node.js
            sudo add-apt-repository ppa:chris-lea/node.js-libs
            sudo add-apt-repository ppa:chris-lea/libjs-underscore
            sudo apt-get update
            sudo apt-get install $(cat requirements/system/ubuntu/apt-packages.txt)

      - run:
          name: install dependencies
          command: |
            python -m virtualenv virtualenv
            . virtualenv/bin/activate
            pip install -r requirements/edx/base.txt
            pip install -r requirements/philu/base.txt

      - save_cache:
          paths:
            - ./virtualenv
          key: v1-dependencies-{{ checksum "requirements" }}

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run tests
          command: |
            ./scripts/all-tests.sh
      - store_artifacts:
          path: test-reports
          destination: test-reports
